---
title: "EDA"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Specify all libraries needed
library(tidyverse)
```


```{r}
data17 = read.csv("sqf-2017.csv")
data18 = read.csv("sqf-2018.csv")
data19 = read.csv("sqf-2019.csv")
data18 <- data18 %>% rename(STOP_FRISK_TIME = Stop.Frisk.Time)
data19 <- data19 %>% rename(STOP_FRISK_ID = STOP_ID_ANONY)
pops <- read.csv("precinct_pop.csv")
pops <- pops %>% rename(WHITE = white)
pops <- pops %>% rename(BLACK = black)
pops <- pops %>% rename(OTHER = other)
pops <- pops %>% rename(HISPANIC = hisp_latino)
pops <- pops %>% 
  mutate(PROP_BLACK = BLACK / total_pop)
pops <- pops %>% 
  mutate(PROP_HISP = HISPANIC / total_pop)
popSums <- colSums(pops)
pops <- pops %>%
  mutate(PROP_BLACK_HISP = (BLACK + HISPANIC)/ total_pop)
pops <- pops %>%
  mutate(PROP_TOTAL = (OTHER + WHITE + BLACK)/ total_pop)
prop_black = c()
for(precinct_num in data17$STOP_LOCATION_PRECINCT) {
    append(prop_black, pops$PROP_BLACK[precinct_num])
    }
#data17 <- data17 %>%
#  mutate(PRECINCT_PROP_BLACK = pops$PROP_BLACK[STOP_LOCATION_PRECINCT])
```

```{r}
# Create a combined data set
combined_1718 <- rbind(data17, data18)
combined_1718$SUPERVISING_ACTION_CORRESPONDING_ACTIVITY_LOG_ENTRY_REVIEWED <- NULL
combined_1718$STOP_LOCATION_PREMISES_NAME <- NULL
data19$ASK_FOR_CONSENT_FLG <- NULL
data19$CONSENT_GIVEN_FLG <- NULL
combined_1719 <- rbind(combined_1718, data19)
```

```{r}
# Filter out missing race data, adjust data in certain columns
filtered_1719 <- combined_1719 %>%
  filter(!SUSPECT_RACE_DESCRIPTION == "(null)" & !SUSPECT_RACE_DESCRIPTION == "MALE")
filtered_1719 <- filtered_1719 %>%
  mutate(RACE = if_else(SUSPECT_RACE_DESCRIPTION == "AMERICAN INDIAN/ALASKAN NATIVE"
                        | SUSPECT_RACE_DESCRIPTION == "AMERICAN INDIAN/ALASKAN N", "AMER IND", SUSPECT_RACE_DESCRIPTION))
filtered_1719 <- filtered_1719 %>%
  mutate(RACE = if_else(RACE == "ASIAN / PACIFIC ISLANDER", "ASIAN/PAC.ISL", RACE))
filtered_1719 <- filtered_1719 %>%
  mutate(RACE = if_else(RACE == "WHITE HISPANIC", "W. HISP.", RACE))
filtered_1719 <- filtered_1719 %>%
  mutate(RACE = if_else(RACE == "BLACK HISPANIC", "B. HISP.", RACE))
filtered_1719$RACE <- fct_relevel(filtered_1719$RACE, "WHITE", "ASIAN/PAC.ISL", "W. HISP.", "B. HISP.", "BLACK", "AMER IND")
filtered_1719 <- filtered_1719 %>%
  mutate(ARRESTED = if_else(SUSPECT_ARRESTED_FLAG == "Y", 1, 0))
filtered_1719 <- filtered_1719 %>%
  mutate(SUSPECTED_VIOLENCE = if_else(SUSPECTED_CRIME_DESCRIPTION == "ROBBERY" | SUSPECTED_CRIME_DESCRIPTION == "ASSAULT" | SUSPECTED_CRIME_DESCRIPTION == "RAPE" | SUSPECTED_CRIME_DESCRIPTION == "MURDER" | SUSPECTED_CRIME_DESCRIPTION == "TERRORISM" | SUSPECTED_CRIME_DESCRIPTION == "FORCIBLE TOUCHING" | SUSPECTED_CRIME_DESCRIPTION == "RECKLESS ENDANGERMENT" | SUSPECTED_CRIME_DESCRIPTION == "MENACING", 1, 0))
filtered_1719 <- filtered_1719 %>%
  mutate(SUSPECT_DRUG_CATEGORY = if_else(SUSPECTED_CRIME_DESCRIPTION == "CRIMINAL POSSESSION OF MARIHUANA" | SUSPECTED_CRIME_DESCRIPTION == "CRIMINAL POSSESSION OF CONTROLLED SUBSTANCE" | SUSPECTED_CRIME_DESCRIPTION == "CRIMINAL SALE OF MARIHUANA" | SUSPECTED_CRIME_DESCRIPTION == "CRIMINAL SALE OF CONTROLLED SUBSTANCE", 1, 0))
filtered_1719 <- filtered_1719 %>%
  mutate(SUSPECT_SEX_CATEGORY = if_else(SUSPECTED_CRIME_DESCRIPTION == "RAPE" | SUSPECTED_CRIME_DESCRIPTION == "PROSTITUTION" | SUSPECTED_CRIME_DESCRIPTION == "FORCIBLE TOUCHING" | SUSPECTED_CRIME_DESCRIPTION == "CRIMINAL SALE OF CONTROLLED SUBSTANCE", "SEX RELATED", "NON-SEX RELATED"))
filtered_1719 <- filtered_1719 %>%
  mutate(PHYSICAL_FORCE_USED = if_else(PHYSICAL_FORCE_CEW_FLAG == "Y" | PHYSICAL_FORCE_DRAW_POINT_FIREARM_FLAG == "Y" | PHYSICAL_FORCE_OC_SPRAY_USED_FLAG == "Y" | PHYSICAL_FORCE_OTHER_FLAG == "Y" | PHYSICAL_FORCE_RESTRAINT_USED_FLAG == "Y" | PHYSICAL_FORCE_WEAPON_IMPACT_FLAG == "Y", 1, 0))
```

```{r}
#filtered_1719 <- filtered_1719 %>%
#  filter(!SUSPECT_HEIGHT == "(null)" & !SUSPECT_HEIGHT == "#NULL!")
#filtered_1719$SUSPECT_HEIGHT <- as.numeric(filtered_1719$SUSPECT_HEIGHT)
#filtered_1719 <- filtered_1719 %>%
#  filter(!SUSPECT_HEIGHT == 60.11)
#filtered_1719 <- filtered_1719 %>%
#  filter(!SUSPECT_WEIGHT == "(null)")
#filtered_1719$SUSPECT_WEIGHT <- as.numeric(filtered_1719$SUSPECT_WEIGHT)
#filtered_1719 <- filtered_1719 %>%
#  filter(!SUSPECT_WEIGHT == 0 & !SUSPECT_WEIGHT == 1)
filtered_1719 <- filtered_1719 %>%
  mutate(WEAPON_FOUND = if_else(WEAPON_FOUND_FLAG == "(", "N", WEAPON_FOUND_FLAG))
filtered_1719 <- filtered_1719 %>%
  mutate(SUSPECT_SEX = if_else(SUSPECT_SEX == "(null)", "UNSPECIFIED", SUSPECT_SEX))
#filtered_1719 <- filtered_1719 %>%
#  filter(!SUSPECT_REPORTED_AGE == "(null)")
#filtered_1719$SUSPECT_REPORTED_AGE <- as.numeric(filtered_1719$SUSPECT_REPORTED_AGE)
```



```{r}
# Univariate EDA
ggplot(data = filtered_1719, aes(x = RACE)) +
  geom_bar() +
  labs(x = "Race of Suspect", y = 
         "Frequency", title = "Race of Suspects in SQF Events")
ggplot(data = filtered_1719, aes(x = SUSPECTED_VIOLENCE)) +
  geom_bar() +
  labs(title = "Number Arrested in SQF Events")
ggplot(data = filtered_1719, aes(x = ARRESTED)) +
  geom_bar() +
  labs(title = "Number Arrested in SQF Events")
barplot(popSums[3:6], main = "Population Totals by Race")
mosaicplot(filtered_1719$RACE ~ filtered_1719$PHYSICAL_FORCE_USED, data = filtered_1719)
#ggplot(data = filtered_1719, aes(group = SUSPECTED_VIOLENCE, x = SUSPECTED_VIOLENCE, y = SUSPECT_HEIGHT)) +
#  geom_boxplot() +
#  labs(title = "Effect of Height on Suspected Violent Crime")
#ggplot(data = filtered_1719, aes(group = SUSPECTED_VIOLENCE, x = SUSPECTED_VIOLENCE, y = SUSPECT_WEIGHT)) +
#  geom_boxplot() +
#  labs(title = "Effect of Weight on Suspected Violent Crime")
#ggplot(data = filtered_1719, aes(group = SUSPECTED_VIOLENCE, x = SUSPECTED_VIOLENCE, y = SUSPECT_REPORTED_AGE)) +
#  geom_boxplot() +
#  labs(title = "Effect of Age on Suspected Violent Crime")
```

```{r}
mosaicplot(filtered_1719$SUSPECTED_VIOLENCE ~ filtered_1719$WEAPON_FOUND, data = filtered_1719)
mosaicplot(filtered_1719$SUSPECT_SEX ~ filtered_1719$SUSPECTED_VIOLENCE, data = filtered_1719)
#mosaicplot(filtered_1719$SUSPECTED_VIOLENCE ~ filtered_1719$SUSPECT_REPORTED_AGE, data = filtered_1719)
mosaicplot(filtered_1719$STOP_WAS_INITIATED ~ filtered_1719$SUSPECTED_VIOLENCE, data = filtered_1719)
```


```{r}
sum(filtered_1719$SUSPECTED_CRIME_CATEGORY == 1 & filtered_1719$RACE == "BLACK")/sum(filtered_1719$RACE == "BLACK")
sum(filtered_1719$SUSPECTED_CRIME_CATEGORY == 1 & filtered_1719$RACE == "WHITE")/sum(filtered_1719$RACE == "WHITE")
sum(filtered_1719$ARRESTED == 1 & filtered_1719$RACE == "W. HISP.")/sum(filtered_1719$RACE == "W. HISP.")
sum(filtered_1719$ARRESTED == 1 & filtered_1719$RACE == "B. HISP.")/sum(filtered_1719$RACE == "B. HISP.")
sum(filtered_1719$ARRESTED == 1 & filtered_1719$RACE == "AMER IND")/sum(filtered_1719$RACE == "AMER IND")
sum(filtered_1719$ARRESTED == 1 & filtered_1719$RACE == "ASIAN/PAC.ISL")/sum(filtered_1719$RACE == "ASIAN/PAC.ISL")
sum(filtered_1719$STOP_DURATION_MINUTES)/sum(filtered_1719$RACE == "WHITE")
sum(filtered_1719$STOP_DURATION_MINUTES)/ sum(filtered_1719$RACE == "BLACK")
```

```{r}
#ggplot(data = filtered_1719, aes_string(x = "SUSPECTED_VIOLENCE", y = "SUSPECT_HEIGHT")) +
#  geom_boxplot() +
#  labs(title = "Effect of Height on Suspected Violent Crime")
#ggplot(data = filtered_1719, aes_string(x = "SUSPECTED_VIOLENCE", y = "SUSPECT_HEIGHT")) +
#  geom_boxplot() +
#  labs(title = "Effect of Height on Suspected Violent Crime")
```


```{r}
arrest_model <- glm(SUSPECTED_VIOLENCE ~ RACE + WEAPON_FOUND + SUSPECT_BODY_BUILD_TYPE + STOP_WAS_INITIATED, data = filtered_1719)
tidy(arrest_model)
```


